Process Process-1:
Traceback (most recent call last):
  File "/home/eilab/anaconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/eilab/anaconda3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/media/becky/GNOME-p3/monopoly_simulator/vanilla_A2C.py", line 74, in worker
    ob, reward, done, info = env.step_after_nochange(data)
  File "/media/becky/GNOME-p3/env/simulator_env/gym_simulator_env/envs/simple_monopoly.py", line 55, in step_after_nochange
    observation_space, reward, terminal, info = self.MonopolyWorld.next_after_nochange(action)
  File "/media/becky/GNOME-p3/env/monopoly_world.py", line 335, in next_after_nochange
    self.a.get_logging_info(self.game_elements, 0, 1)
  File "/media/becky/GNOME-p3/monopoly_simulator/interface.py", line 52, in get_logging_info
    file.write(game_elements['location_sequence'][i['player'].current_position].name +' Card => ' + i['card'].name + '\n')
TypeError: list indices must be integers or slices, not NoneType
Traceback (most recent call last):
  File "vanilla_A2C_main_v4.py", line 279, in <module>
    trainer.train()
  File "vanilla_A2C_main_v4.py", line 110, in train
    self.train_kg()
  File "vanilla_A2C_main_v4.py", line 98, in train_kg
    s_prime, _, done, masked_actions = self.envs.step_after_nochange(a_tf)
  File "/media/becky/GNOME-p3/monopoly_simulator/vanilla_A2C.py", line 144, in step_after_nochange
    return self.step_wait()
  File "/media/becky/GNOME-p3/monopoly_simulator/vanilla_A2C.py", line 125, in step_wait
    results = [master_end.recv() for master_end in self.master_ends] #receive from worker_end #format???
  File "/media/becky/GNOME-p3/monopoly_simulator/vanilla_A2C.py", line 125, in <listcomp>
    results = [master_end.recv() for master_end in self.master_ends] #receive from worker_end #format???
  File "/home/eilab/anaconda3/lib/python3.7/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/home/eilab/anaconda3/lib/python3.7/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/home/eilab/anaconda3/lib/python3.7/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
